import swaggerAutogen from "swagger-autogen";
const swagger = swaggerAutogen();
import config from "config";
const doc = {
  info: {
    version: "1.0", // by default: "1.0.0"
    title: "Neetu kanaujia test Api", // by default: "REST API"
    description: "Documentation", // by default: ""
  },
  host: config.get("swagger_host_url"), // by default: "localhost:3000"
  basePath: "/", // by default: "/"
  schemes: ["http"],
  consumes: ["application/json", "application/x-www-form-urlencoded"],
  produces: ["application/json"],
  tags: [
    {
      name: "Token",
      description: "Token Endpoint",
      summary: "Token Api",
    },
    {
      name: "DB",
      description: "DB Endpoint",
      summary: "DB Api",
      summary: "DB Api",
    },
  ],
  securityDefinitions: {
    AccessToken: {
      type: "apiKey",
      in: "header",
      name: "x-auth-token",
      description: `
            Please provide the valid access token
            x-auth-token : <>Your access token generated by api<> `,
    },
  }, // by default: empty object
  definitions: {
    transaction: {
      amount: 100,
      description: "test",
      type: "credit",
      card_id: "65d47861f9177521bf1e794f",
    },
  },
};
const outputFile = "./resources/views/swagger-api-view.json";
const endpointsFiles = ["./resources/routes/public.routes.js"];
/* NOTE: if you use the express Router, you must pass in the
   'endpointsFiles' only the root file where the route starts,
   such as: index.js, app.js, routes.js, ... */
await swagger(outputFile, endpointsFiles, doc);
